/**
 * AnalystAgent - The "Teacher" for the Hub
 * 
 * Responsibilities:
 * 1. Scans all available intelligence (Docs, Arrests, Investigations).
 * 2. Generates "Intelligence Briefs" summarizing key threats and trends.
 * 3. Saves briefs as documents so they are ingested by the AI brain.
 */

import IntelData from '../TestDataPoint/Intel';
import ArrestData from '../TestDataPoint/ArrestData';
import PrisonData from '../TestDataPoint/PrisonData';
import { Hub } from '../services/CentralHubService';

export class AnalystAgent {
  constructor() {
    this.name = "Senior Analyst (Agent)";
    this.status = "Idle";
    this.lastRun = null;
  }

  async runAnalysis() {
    this.status = "Analyzing Intelligence Data...";
    console.log(`[${this.name}] Starting analysis cycle...`);

    const stats = {
      investigations: IntelData.allInvestigations.length,
      arrests: ArrestData.arrest_data.length,
      prisoners: PrisonData.prisons_data.length,
      documents: this.getUploadedDocsCount()
    };

    // 1. Identify High Priority Threats (Mock logic for now, could use NeuralNet)
    const activeThreats = IntelData.allInvestigations.filter(i => i.priority === 'high' && i.status !== 'closed');
    
    // 2. Identify Crime Hotspots (Simple frequency map)
    const locations = {};
    [...IntelData.allInvestigations, ...ArrestData.arrest_data].forEach(item => {
      if (item.location) {
        locations[item.location] = (locations[item.location] || 0) + 1;
      }
    });
    const topLocations = Object.entries(locations)
      .sort((a, b) => b[1] - a[1])
      .slice(0, 3)
      .map(([loc, count]) => `${loc} (${count} incidents)`);

    // 3. Generate Briefing Content
    const briefContent = `
INTELLIGENCE BRIEFING - ${new Date().toLocaleDateString()}
GENERATED BY: ${this.name}

1. SITUATION OVERVIEW
   Total Active Investigations: ${IntelData.allInvestigations.filter(i => i.status !== 'closed').length}
   Recent Arrests: ${ArrestData.arrest_data.length} (Last 30 days)
   Prison Population Tracked: ${stats.prisoners}

2. HIGH PRIORITY THREATS
   ${activeThreats.length > 0 ? activeThreats.map(t => `- [${t.intelType}] at ${t.location}: ${t.desc}`).join('\n   ') : 'No immediate high-priority threats detected.'}

3. GEOGRAPHIC HOTSPOTS
   ${topLocations.join(', ')}

4. ANALYSIS
   Current data indicates a concentration of activity in ${topLocations[0]?.split('(')[0] || 'Unknown regions'}. 
   Recommended increased surveillance in these sectors.
    `.trim();

    // 4. Save as a System Document
    this.saveBriefing(briefContent);

    this.status = "Idle - Briefing Generated";
    this.lastRun = new Date();
    
    return {
      success: true,
      summary: "Daily Intelligence Briefing generated and filed.",
      brief: briefContent
    };
  }

  getUploadedDocsCount() {
    try {
      const docs = JSON.parse(localStorage.getItem('case_documents') || '[]');
      return docs.length;
    } catch {
      return 0;
    }
  }

  saveBriefing(content) {
    try {
      const docs = JSON.parse(localStorage.getItem('case_documents') || '[]');
      const newDoc = {
        id: `brief_${Date.now()}`,
        name: `Intel_Brief_${new Date().toISOString().split('T')[0]}.txt`,
        type: 'text/plain',
        content: content,
        uploadDate: new Date().toISOString(),
        size: '1 KB',
        category: 'Legal', // Classified as Legal/Official
        analysis: {
          summary: { description: "Automated Intelligence Briefing generated by Analyst Agent.", important: true },
          entities: { people: ["Analyst Agent"], crimeTypes: ["Summary"], places: [] }
        },
        desc: "System generated intelligence summary."
      };
      
      docs.unshift(newDoc);
      localStorage.setItem('case_documents', JSON.stringify(docs));
      console.log(`[${this.name}] Briefing saved to central documents.`);
    } catch (e) {
      console.error("Failed to save briefing:", e);
    }
  }

  /**
   * Provides a specific intelligence insight for a search subject (person or plate).
   */
  async getSubjectInsight(query, type = 'name') {
    const q = query.toLowerCase().trim();
    const insights = [];
    
    // FETCH FROM THE MASTER BRAIN (HUB)
    const profile = Hub.getConnectedProfile(q);
    
    const relevantInvs = profile.investigations;
    const relevantArrests = profile.arrests;
    const docMentions = profile.hubMentions;

    if (relevantInvs.length > 0 || relevantArrests.length > 0 || profile.prison || docMentions.length > 0) {
      if (relevantInvs.length > 0) {
        insights.push(`Subject linked to ${relevantInvs.length} investigations.`);
      }
      if (relevantArrests.length > 0) {
        insights.push(`Subject has ${relevantArrests.length} confirmed arrest records.`);
      }
      if (profile.prison) {
        insights.push(`WARNING: Subject has a PRISON RECORD for ${profile.prison.crime}.`);
      }
      if (docMentions.length > 0) {
        insights.push(`CROSS-REFERENCE: Subject detected in ${docMentions.length} analyzed documents/reports.`);
      }
      
      // Geographic Insight
      const locs = [...relevantInvs, ...relevantArrests].map(i => i.location).filter(Boolean);
      if (locs.length > 0) {
        insights.push(`Primary operation sectors: ${[...new Set(locs)].join(', ')}.`);
      }
    } else {
      insights.push("No immediate criminal or investigative flags found in core databases.");
    }

    // Agent Recommendation Logic
    let recommendation = "Standard monitoring.";
    let threatLevel = 'Low';

    if (profile.prison || relevantInvs.some(i => i.priority === 'high')) {
      threatLevel = 'High';
      recommendation = "URGENT: Subject is high-threat. Multi-agency alert recommended.";
    } else if (profile.isSuspect || docMentions.length > 0) {
      threatLevel = 'Elevated';
      recommendation = "CAUTION: Patterns identified in both documents and records.";
    }

    return {
      agentName: this.name,
      timestamp: new Date().toISOString(),
      findings: insights,
      recommendation,
      threatLevel
    };
  }
}
